[package]
name = "package_mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
pnp = { path = "../../pnp/pnp" }
criteria = { path = "../../common/criteria" }
util = { path = "../../common/util" }

regex = { workspace = true }

[features]
testing = []