[package]
name = "gerber_viewer_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
# Logging
log = "0.4"
env_logger = "0.11"

# GUI Framework
egui = "0.31.1"
eframe = { version = "0.31.1", features = ["default"] }
epaint = "0.31.1"
egui_extras = "0.31.1"
egui_taffy = "0.7.0"

# File Dialog
rfd = "0.15.2"

# Gerber rendering, types and parser
gerber_viewer = { path = "../gerber_viewer", features = ["egui", "types", "parser"] }

# Errors
thiserror = "2.0.12"

# Math
rand = "0.9.1"
lyon = "1.0"

gerber-types = { git = "https://github.com/hydra/gerber-types-rs.git", rev = "d93cb0d4954c39cf17f924e003b5b396aeaaafd1"}
