[package]
name = "package_mapper"
version = "0.1.0"
edition = "2024"

[dependencies]
pnp = { path = "../pnp"}
criteria = { path = "../criteria"}
util = { path = "../util"}

regex = { workspace = true }

[features]
testing = []