[package]
name = "planner_gui_egui"
version = "0.1.0"
edition = "2024"

[dependencies]
planner_app = { path = "../planner_app" }

# tasks/async
tokio = { workspace = true, features = ["full"]}
futures =  { workspace = true }
async-std =  { workspace = true }

# serialization
serde = { workspace = true, features = ["derive"] }
# Required for form validation (!)
serde_json = { workspace = true }

# gui
egui = { workspace = true }
egui_taffy = {  workspace = true }
egui-i18n = { workspace = true }

# i18n
unic-langid = { workspace = true, features = ["macros"]}
fluent = { workspace = true }
fluent-bundle = { workspace = true }

# logging
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing = { workspace = true }
regex = { workspace = true }

# form validation
validator = { workspace = true }

# other
slotmap = { workspace = true }
thiserror = { workspace = true }
petgraph = { workspace = true }
