[package]
name = "egui_vertical_stack_simple"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.31.1"
eframe = "0.31.1"
egui_vertical_stack = { path = "../.."}

# cargo workaround
[workspace]