[package]
name = "server_rt_core"
version = "0.1.0"
edition = "2024"

[dependencies]
server_rt_shared = { path = "../server_rt_shared" }
rt_circular_buffer = { path = "../rt_circular_buffer" }
rt_time = { path = "../rt_time" }
iceoryx2 = "0.7.0"